experiment:
  name: reddit_comments_100_test
  submit_job: True
  log: True

data:
  dataset: Reddit Comments
  year: 2019
  month: 10

clients:
  n_clients: 100
  n_tokens: 6400
  train_ratio: 0.8

language_model:
  vocab_size: 20_000
  batch_size: 32
  bptt_len: 30
  rnn_type: LSTM
  embedding_dim: 32
  hidden_dim: 90
  n_layers: 2

federated_parameters:
  n_rounds: 150
  clients_p_round: 100
  n_epochs: 2
  client_lr: 0.01