experiment:
  name: reddit_comments_100_test
  submit_job: True
  log_dir: 'homes/spd16/Documents/tensorboard_google_arch'

data:
  dataset: Reddit Comments
  year: 2019
  month: 10

clients:
  n_clients: 100
  n_tokens: 6400
  train_ratio: 0.8

language_model:
  vocab_size: 10_000
  batch_size: 50
  bptt_len: 15
  rnn_type: GRU
  embedding_dim: 96
  hidden_dim: 670
  n_layers: 1

federated_parameters:
  n_rounds: 1000
  clients_p_round: 3
  n_epochs: 1
  client_lr: 0.001
