name: run-experiment
on:
  pull_request:
    branches: [ master ]
jobs:
  submit-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ci_requirements.txt
    - name: build-config
      run: python build_config.py
